import { Geist, Geist_Mono, Eczar, Fraunces } from "next/font/google";
import "./globals.css";

//Context for using UseState functionality for saving recipes
import { SavedRecipesProvider } from "@/lib/localstorageFunctionality/savedRecipesContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const eczar = Eczar({
  weight: '400',
  subsets: ['latin'],
  variable: '--Eczar'
})

const fraunces = Fraunces({
  weight: '400',
  subsets: ['latin'],
  variable: '--fraunces'
})

export const metadata = {
  title: "RECIPE INSPIRATION!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${eczar.variable} ${fraunces.variable} antialiased`}
      >
        <SavedRecipesProvider>{children}</SavedRecipesProvider>
      </body>
    </html>
  );
}
